### PR TITLE
Updated README.md with extraUserProperties docs

### PR DESCRIPTION
**Pull request by master-bob**
Added documentation on the certification.extraUserProperties sakai.propertie values, to the best of my understanding of them by reading the code.

### CODE REVIEW

**Comment by bjones86** [comment]
Wow, thanks for taking the initiative on this @master-bob! I'll give you a little more context though, as they're not used for possible replacement values in a certificate itself. Rather, they're just extra properties you can configure to see in the results table.

For example, at our institution there was a need to display student numbers (provided through LDAP) in several tools, one of which was certification. So we developed this little utility and eventually duplicated it in several places.

That being said, we are in the process of refactoring this extraUserProps stuff into a centralized provider style in kernel, following Matthew Bucket's examples. So with that in mind, the actual implementation of this will eventually be ripped out of Certification, you will be able to use the provider in any tool.

**Comment by master-bob** [comment]
Okay. I see.

extraUserProperties is used to display properties from user.getProperties.

**Comment by bjones86** [comment]
I can take a stab at modifying the content in your PR later today if you'd like.

**Comment by bjones86** [comment]
I finally had a few minutes to spin on updating this. Take a look see and let me know if it looks good to you. Cheers!

**Comment by master-bob** [comment]
I made a minor spelling fix. Looks good now!

Thank you for your help.

**Comment by bjones86** [comment]
Thanks to you as well, good sir!

**Pull request merged**
